version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'
  front-end:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./front-end
    volumes:
      - /app/node_modules
      - ./front-end:/app
  back-end:
    build:
      dockerfile: Dockerfile
      context: './back-end'
    volumes:
      - ./uploads:/uploads